connect / as sysdba
create spfile from pfile;
startup nomount
CREATE DATABASE ORCL
EXTENT MANAGEMENT LOCAL
DEFAULT TEMPORARY TABLESPACE temp
UNDO TABLESPACE undotbs1
DEFAULT TABLESPACE users;
CREATE TABLESPACE apps_tbs LOGGING 
     DATAFILE '/u01/app/oracle/oradata/ORCL/apps01.dbf' 
     SIZE 500M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED 
     EXTENT MANAGEMENT LOCAL;
CREATE TABLESPACE indx_tbs LOGGING 
     DATAFILE '/u01/app/oracle/oradata/ORCL/indx01.dbf' 
     SIZE 100M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED 
     EXTENT MANAGEMENT LOCAL;
CREATE USER ORCL_USER IDENTIFIED BY "admin2DB" 
    DEFAULT TABLESPACE USERS 
    TEMPORARY TABLESPACE TEMP 
    QUOTA UNLIMITED ON USERS 
    QUOTA UNLIMITED ON APPS_TBS;
    QUOTA UNLIMITED ON INDX_TBS;
CREATE ROLE ORCL_USERS;
GRANT CREATE session, CREATE table, CREATE trigger, CREATE sequence, CREATE view,
    CREATE procedure, CREATE synonym TO ORCL_USERS;
GRANT ORCL_USERS TO ORCL_USER;
exit