connect / as sysdba
CREATE USER ORCL_USER IDENTIFIED BY "admin2DB" 
    DEFAULT TABLESPACE USERS 
    TEMPORARY TABLESPACE TEMP 
    QUOTA UNLIMITED ON USERS;
CREATE ROLE ORCL_USERS;
GRANT CREATE session, CREATE table, CREATE trigger, CREATE sequence, CREATE view,
    CREATE procedure, CREATE synonym TO ORCL_USERS;
GRANT ORCL_USERS TO ORCL_USER;
exit
