#!/bin/bash

cat >> /home/oracle/.bash_profile <<EOF
ORACLE_BASE=/u01/app/oracle
export ORACLE_BASE

ORACLE_SID=ORCL
export ORACLE_SID

ORACLE_HOME=$ORACLE_BASE/product/12.1.0/db_1
export ORACLE_HOME

PATH=$ORACLE_HOME/bin:$PATH
export PATH
EOF

mount -t tmpfs shmfs -o size=4g /dev/shm

date
echo "Creating database..."
su -s /bin/bash oracle -c "dbca -silent -createDatabase -templateName General_Purpose.dbc -sid ORCL -responseFile NO_VALUE -characterSet AL32UTF8 -memoryPercentage 30 -emConfiguration LOCAL -gdbname orcl -sysPassword admin2DB -systemPassword admin2DB -datafileDestination /u01/app/oracle/oradata/data -recoveryAreaDestination /u01/app/oracle/oradata/flash_recovery_area -initParams control_files='/u01/app/oracle/oradata/control1/ora_control',control_files='/u01/app/oracle/oradata/control2/ora_control',audit_file_dest='/u01/app/oracle/oradata/adump',diagnostic_dest='/u01/app/oracle/oradata/diag'" 

echo "Creating ORCL_USER..."
su -s /bin/bash oracle -c "sqlplus /nolog @?/config/scripts/createdb.sql"
echo ""

echo "Shutting down DB..."
su -s /bin/bash oracle -c "sqlplus / as sysdba @?/config/scripts/oraShutdown.sql"
