#!/bin/bash

mount -t tmpfs shmfs -o size=4g /dev/shm

date
su -s /bin/bash oracle -c "cd /tmp/install/database/ && ./runInstaller -ignoreSysPrereqs -ignorePrereq -silent -noconfig -showProgress -responseFile /tmp/db_install.rsp"
while ps -ef | grep java | grep -v grep > /dev/null 2>&1; do
    sleep 10
done;
