#!/bin/bash

/home/oracle/client/runInstaller -ignoreSysPrereqs -ignorePrereq -silent -showProgress -responseFile /home/oracle/client_install.rsp
while ps -ef | grep java | grep -v grep > /dev/null 2>&1; do
    sleep 10
done;
